### ISSUE TITLE
footer.php business hours

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/evr-summer-2017#9]
At the moment all business hours etc... are hard-coded in the footer.

I'd recommend trying to use a widget for this, e.g. the one we used for inhabitent.

**Comment by ghost** [comment]
done

**Comment by rcass** [comment]
Just checking to see if this was done and I noticed in footer.php I still see hard coded content in there. 
I would also make that accessible to the client.
I made a new ticket for that!  Here is the new ticket -> #12
